recon: LMR
user: dce725
domain: gmail.com
uniqueID: '17722313126579804'
useGitHubActions: 'true'
recon_period:
  - '850'
  - '1850'
recon_seeds:
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
recon_loc_rad: '25000'
proxy_assim_frac: '0.75'
proxy_nens: '100'
prior_annualize_months:
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'
prior_anom_period:
  - '850'
  - '1850'
language: en
